[build]
  command = "npm run build"
  publish = "dist/protax"
  functions = "netlify/functions"

[build.environment]
  VITE_SUPABASE_URL = "https://asdthnxphqjpxzyhpylr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
 

[[redirects]]
  from = "/login-share.html"
  to = "/login-share.html"
  status = 200

[[redirects]]
  from = "/index-share.html"
  to = "/index-share.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite --port 5173"
  port = 8888
  targetPort = 5173
  publish = "dist/protax"
  autoLaunch = true
  framework = "#custom"

[dev.environment]
  VITE_SUPABASE_URL = "https://asdthnxphqjpxzyhpylr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**/*"]
  external_node_modules = []

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://www.google.com https://www.gstatic.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://*.unsplash.com https://*.supabase.co https://storage.googleapis.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com https://o4508848989929472.ingest.us.sentry.io;
      frame-src https://www.google.com https://www.gstatic.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-ancestors 'none';
    """
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Cross-Origin-Opener-Policy = "same-origin"